CSCI_NAME = body
PROTO_SOURCES = proto/gait.proto proto/eyes.proto proto/attitude.proto
PROTO_INCLUDE = ../common/proto

.PHONY: all
all: proto

.PHONY: clean
clean: clean-proto

# *** Protocol buffers ***
include ../proto.mk
