CSCI_NAME = common
PROTO_SOURCES = proto/common.proto proto/logging.proto proto/vectors.proto

.PHONY: all
all: proto

.PHONY: clean
clean: clean-proto

# *** Protocol buffers ***
include ../proto.mk

